// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vahallan_Ingredient_Aggregator.Data;

#nullable disable

namespace Vahallan_Ingredient_Aggregator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250831151620_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "15872cac-a9ef-489b-960f-84126587473d",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "6ad17ed5-7771-4dae-88dd-78254e34e888",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3a5ac411-cd93-4802-a834-aa2eaaad964d",
                            Email = "admin@yourapp.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@YOURAPP.COM",
                            NormalizedUserName = "ADMIN@YOURAPP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEENZXYbAYyF5ia3L95aKlI5RL6vLPH8UFOJuiW8KLAJ8V0OKw1Oz/8nRfPEf3EPa+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3edf5685-1938-4ee7-a824-923c2464557b",
                            TwoFactorEnabled = false,
                            UserName = "admin@yourapp.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeTags", (string)null);
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccuracyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("ShowInIngredientsList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("StoredQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StoredUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BaseIngredientComponent");

                    b.HasDiscriminator<string>("Type").HasValue("BaseIngredientComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 1,
                            Quantity = 16m,
                            RecipeId = 8,
                            Unit = "oz"
                        },
                        new
                        {
                            Id = 2,
                            IngredientId = 2,
                            Quantity = 4m,
                            RecipeId = 8,
                            Unit = "count"
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 3,
                            Quantity = 20m,
                            RecipeId = 8,
                            Unit = "count"
                        },
                        new
                        {
                            Id = 4,
                            IngredientId = 4,
                            Quantity = 2m,
                            RecipeId = 8,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 5,
                            IngredientId = 5,
                            Quantity = 2m,
                            RecipeId = 8,
                            Unit = "tbsp"
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 6,
                            Quantity = 0.5m,
                            RecipeId = 8,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 7,
                            IngredientId = 7,
                            Quantity = 0.25m,
                            RecipeId = 8,
                            Unit = "tsp"
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Photo.RecipePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainPhoto")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipePhotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentType = "image/jpeg",
                            Description = "Classic Caprese Salad with alternating slices of mozzarella and tomato",
                            FileName = "caprese-main.jpg",
                            FilePath = "/recipe-photos/originals/caprese-main.jpg",
                            FileSize = 19661L,
                            IsApproved = true,
                            IsMain = true,
                            IsMainPhoto = false,
                            RecipeId = 8,
                            ThumbnailPath = "/recipe-photos/thumbnails/caprese-main.jpg",
                            UploadedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2227),
                            UploadedById = "system"
                        },
                        new
                        {
                            Id = 2,
                            ContentType = "image/jpeg",
                            Description = "Caprese Salad from a different angle",
                            FileName = "caprese-salad-recipe-1.jpg",
                            FilePath = "/recipe-photos/originals/caprese-salad-recipe-1.jpg",
                            FileSize = 18432L,
                            IsApproved = true,
                            IsMain = false,
                            IsMainPhoto = false,
                            RecipeId = 8,
                            ThumbnailPath = "/recipe-photos/thumbnails/caprese-salad-recipe-1.jpg",
                            UploadedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2230),
                            UploadedById = "system"
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", b =>
                {
                    b.HasBaseType("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent");

                    b.Property<decimal>("CaloriesPerServing")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CostPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPromoted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemIngredient")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PromotionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PromotionStartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ServingsPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SystemIngredientId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2114),
                            CreatedById = "system",
                            Name = "Fresh Mozzarella",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 28.35m,
                            StoredUnit = "g",
                            Type = "Ingredient",
                            Unit = "oz",
                            CaloriesPerServing = 70m,
                            CostPerPackage = 5.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 16m
                        },
                        new
                        {
                            Id = 2,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2121),
                            CreatedById = "system",
                            Name = "Ripe Tomatoes",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 1m,
                            StoredUnit = "count",
                            Type = "Ingredient",
                            Unit = "count",
                            CaloriesPerServing = 22m,
                            CostPerPackage = 3.00m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 4m
                        },
                        new
                        {
                            Id = 3,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2125),
                            CreatedById = "system",
                            Name = "Fresh Basil Leaves",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 1m,
                            StoredUnit = "count",
                            Type = "Ingredient",
                            Unit = "count",
                            CaloriesPerServing = 1m,
                            CostPerPackage = 2.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 30m
                        },
                        new
                        {
                            Id = 4,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2128),
                            CreatedById = "system",
                            Name = "Extra Virgin Olive Oil",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 14.7868m,
                            StoredUnit = "ml",
                            Type = "Ingredient",
                            Unit = "tbsp",
                            CaloriesPerServing = 120m,
                            CostPerPackage = 8.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 33.8m
                        },
                        new
                        {
                            Id = 5,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2132),
                            CreatedById = "system",
                            Name = "Balsamic Vinegar",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 14.7868m,
                            StoredUnit = "ml",
                            Type = "Ingredient",
                            Unit = "tbsp",
                            CaloriesPerServing = 14m,
                            CostPerPackage = 5.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 16.9m
                        },
                        new
                        {
                            Id = 6,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2136),
                            CreatedById = "system",
                            Name = "Salt",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 4.92892m,
                            StoredUnit = "ml",
                            Type = "Ingredient",
                            Unit = "tsp",
                            CaloriesPerServing = 0m,
                            CostPerPackage = 0.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 156m
                        },
                        new
                        {
                            Id = 7,
                            AccuracyLevel = 0,
                            Collection = "",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2139),
                            CreatedById = "system",
                            Name = "Black Pepper",
                            Quantity = 1m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 4.92892m,
                            StoredUnit = "ml",
                            Type = "Ingredient",
                            Unit = "tsp",
                            CaloriesPerServing = 0m,
                            CostPerPackage = 3.99m,
                            IsPromoted = false,
                            IsSystemIngredient = true,
                            ServingsPerPackage = 144m
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", b =>
                {
                    b.HasBaseType("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<decimal>("NumberOfServings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("OriginalRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            AccuracyLevel = 1,
                            Collection = "Appetizers",
                            CreatedAt = new DateTime(2025, 8, 31, 15, 16, 19, 827, DateTimeKind.Utc).AddTicks(2097),
                            CreatedById = "system",
                            Name = "Classic Caprese Salad",
                            Quantity = 4m,
                            ShowInIngredientsList = false,
                            StoredQuantity = 4m,
                            StoredUnit = "serving",
                            Type = "Recipe",
                            Unit = "serving",
                            CookTimeMinutes = 0,
                            Description = "A simple and elegant Italian salad made with fresh mozzarella, tomatoes, and basil.",
                            Instructions = "1. Slice the mozzarella and tomatoes into 1/4-inch thick slices.\r\n2. On a serving plate, alternately arrange the mozzarella and tomato slices in a circular pattern.\r\n3. Tuck fresh basil leaves between the mozzarella and tomato slices.\r\n4. Drizzle with extra virgin olive oil and balsamic vinegar.\r\n5. Season with salt and freshly ground black pepper.\r\n6. Serve immediately at room temperature.",
                            IsPublic = true,
                            NumberOfServings = 4m,
                            PrepTimeMinutes = 15,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.RecipeIngredient", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Photo.RecipePhoto", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", null)
                        .WithMany("Photos")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
