// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vahallan_Ingredient_Aggregator.Data;

#nullable disable

namespace Vahallan_Ingredient_Aggregator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250901184253_initMigration")]
    partial class initMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "20afc4e2-687d-4776-83f9-e0bf3e58554e",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "8a7b8a57-dee2-49ef-a3a3-d6de222034a9",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f5d3eeed-f051-4a58-a211-8030e0ddb58d",
                            Email = "admin@yourapp.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@YOURAPP.COM",
                            NormalizedUserName = "ADMIN@YOURAPP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEExCNkVacy6HOtzxkfKqsz6HDAT/aHrJ83b4y+igrQilbzNPVAYvbHCOoDtTzs++tQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a48f44ac-dc53-41c0-813f-9dadb7fa5745",
                            TwoFactorEnabled = false,
                            UserName = "admin@yourapp.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeTags", (string)null);
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("StoredQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StoredUnit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BaseIngredientComponent");

                    b.HasDiscriminator<string>("Type").HasValue("BaseIngredientComponent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            IngredientId = 101,
                            Quantity = 0.75m,
                            RecipeId = 100,
                            Unit = "gallons"
                        },
                        new
                        {
                            Id = 102,
                            IngredientId = 102,
                            Quantity = 0.5m,
                            RecipeId = 100,
                            Unit = "quarts"
                        },
                        new
                        {
                            Id = 103,
                            IngredientId = 103,
                            Quantity = 0.25m,
                            RecipeId = 100,
                            Unit = "quarts"
                        },
                        new
                        {
                            Id = 104,
                            IngredientId = 104,
                            Quantity = 0.33m,
                            RecipeId = 100,
                            Unit = "quarts"
                        },
                        new
                        {
                            Id = 105,
                            IngredientId = 105,
                            Quantity = 2.5m,
                            RecipeId = 100,
                            Unit = "lbs"
                        },
                        new
                        {
                            Id = 106,
                            IngredientId = 106,
                            Quantity = 1m,
                            RecipeId = 100,
                            Unit = "oz"
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Photo.RecipePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainPhoto")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipePhotos");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ContentType = "image/jpeg",
                            Description = "Eden wallpaper pattern showing metallic texture with cork accents",
                            FileName = "eden-main.jpg",
                            FilePath = "/recipe-photos/originals/eden-main.jpg",
                            FileSize = 25000L,
                            IsApproved = true,
                            IsMain = true,
                            IsMainPhoto = false,
                            RecipeId = 100,
                            ThumbnailPath = "/recipe-photos/thumbnails/eden-main.jpg",
                            UploadedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8506),
                            UploadedById = "system"
                        },
                        new
                        {
                            Id = 102,
                            ContentType = "image/jpeg",
                            Description = "Close-up detail of Eden pattern texture and metallic finish",
                            FileName = "eden-detail.jpg",
                            FilePath = "/recipe-photos/originals/eden-detail.jpg",
                            FileSize = 18500L,
                            IsApproved = true,
                            IsMain = false,
                            IsMainPhoto = false,
                            RecipeId = 100,
                            ThumbnailPath = "/recipe-photos/thumbnails/eden-detail.jpg",
                            UploadedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8509),
                            UploadedById = "system"
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", b =>
                {
                    b.HasBaseType("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent");

                    b.Property<decimal>("CostPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SystemIngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitsPerPackage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ingredient");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8473),
                            CreatedById = "system",
                            Name = "Off-White Egg Latex Paint",
                            Quantity = 3m,
                            StoredQuantity = 3m,
                            StoredUnit = "gallons",
                            Type = "Ingredient",
                            Unit = "gallons",
                            CostPerPackage = 45.99m,
                            MaterialType = "Paint",
                            UnitsPerPackage = 1m,
                            Vendor = "Pittsburgh Paints"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8482),
                            CreatedById = "system",
                            Name = "Pearl Metallic Paint",
                            Quantity = 2m,
                            StoredQuantity = 2m,
                            StoredUnit = "quarts",
                            Type = "Ingredient",
                            Unit = "quarts",
                            CostPerPackage = 24.95m,
                            MaterialType = "Metallic Paint",
                            UnitsPerPackage = 1m,
                            Vendor = "Modern Masters"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8486),
                            CreatedById = "system",
                            Name = "Champagne Metallic Paint",
                            Quantity = 1.5m,
                            StoredQuantity = 1.5m,
                            StoredUnit = "quarts",
                            Type = "Ingredient",
                            Unit = "quarts",
                            CostPerPackage = 26.50m,
                            MaterialType = "Metallic Paint",
                            UnitsPerPackage = 1m,
                            Vendor = "Modern Masters"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8489),
                            CreatedById = "system",
                            Name = "Polycrylic Semi-Gloss Sealer",
                            Quantity = 4m,
                            StoredQuantity = 4m,
                            StoredUnit = "quarts",
                            Type = "Ingredient",
                            Unit = "quarts",
                            CostPerPackage = 18.75m,
                            MaterialType = "Sealer",
                            UnitsPerPackage = 1m,
                            Vendor = "Pittsburgh Paints"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8493),
                            CreatedById = "system",
                            Name = "Natural Cork Pieces",
                            Quantity = 15m,
                            StoredQuantity = 15m,
                            StoredUnit = "lbs",
                            Type = "Ingredient",
                            Unit = "lbs",
                            CostPerPackage = 89.99m,
                            MaterialType = "Texture",
                            UnitsPerPackage = 20m,
                            Vendor = "Cork Supply Co"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8497),
                            CreatedById = "system",
                            Name = "White Gold Glitter",
                            Quantity = 8m,
                            StoredQuantity = 8m,
                            StoredUnit = "oz",
                            Type = "Ingredient",
                            Unit = "oz",
                            CostPerPackage = 12.95m,
                            MaterialType = "Glitter",
                            UnitsPerPackage = 4m,
                            Vendor = "Craft Essentials"
                        });
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", b =>
                {
                    b.HasBaseType("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent");

                    b.Property<int>("AccuracyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IsPublic")
                        .HasColumnType("decimal");

                    b.Property<int?>("OriginalRecipeId")
                        .HasColumnType("int");

                    b.Property<string>("PatternCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("ShowInIngredientsList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("StandardSheetSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(100m);

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Recipe");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2025, 9, 1, 18, 42, 52, 345, DateTimeKind.Utc).AddTicks(8458),
                            CreatedById = "system",
                            Name = "Eden",
                            Quantity = 100m,
                            StoredQuantity = 1m,
                            StoredUnit = "serving",
                            Type = "Recipe",
                            Unit = "sq ft",
                            AccuracyLevel = 1,
                            Collection = "Enchanted Collection",
                            CookTimeMinutes = 0,
                            Description = "Luxurious textured wallpaper with metallic accents and organic cork elements, creating an enchanted forest ambiance.",
                            Instructions = "1. Prepare the wall surface by cleaning and priming if necessary.\r\n2. Apply base coat of Off-White Egg latex paint using roller in even strokes.\r\n3. Allow base coat to dry completely (4-6 hours).\r\n4. Apply Pearl metallic paint using sea sponge in circular motions for texture.\r\n5. While Pearl is still tacky, lightly dab Champagne metallic accents.\r\n6. Sprinkle White Gold glitter sparingly over wet metallic areas.\r\n7. Press cork pieces into designated areas while paint is workable.\r\n8. Allow to dry overnight before applying Polycrylic sealer with brush.\r\n9. Apply thin, even coat of sealer avoiding drips or runs.\r\n10. Allow 24 hours cure time before normal use.",
                            IsPublic = 1m,
                            PatternCode = "EDEN-001",
                            PrepTimeMinutes = 45,
                            ShowInIngredientsList = false,
                            StandardSheetSize = 25m,
                            Version = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.RecipeIngredient", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Photo.RecipePhoto", b =>
                {
                    b.HasOne("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", null)
                        .WithMany("Photos")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.BaseIngredientComponent", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("Vahallan_Ingredient_Aggregator.Models.Components.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
